# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoNotes < Formula
  desc ""
  homepage "https://github.com/claushellsing/homebrew-goNotes"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/claushellsing/goNotes/releases/download/v0.1.3/goNotes_Darwin_arm64.tar.gz"
      sha256 "c618f78201f3fa1a00d35b16aef094b2014f068ed57c5b0eb4599bf37f821434"

      def install
        bin.install "goNotes"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/claushellsing/goNotes/releases/download/v0.1.3/goNotes_Darwin_x86_64.tar.gz"
      sha256 "34a36ccb879fef47247a87105cb2de3a017e187f2688c05cf2d8aa8b0ec67046"

      def install
        bin.install "goNotes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/claushellsing/goNotes/releases/download/v0.1.3/goNotes_Linux_arm64.tar.gz"
      sha256 "e2447fb541c61a5c44a569ac09f5edd348bae704fa69a38d65213ed7c74ccddf"

      def install
        bin.install "goNotes"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/claushellsing/goNotes/releases/download/v0.1.3/goNotes_Linux_x86_64.tar.gz"
      sha256 "01a1a040c7e9d3dd384435661756b8f3aa645cc25c35b191217593f5d218d43e"

      def install
        bin.install "goNotes"
      end
    end
  end
end
